--- 

- hosts: all
  tasks:
  - name: create a file on a remote machine
    file:
      dest: ./file
      state: '{{file_state}}'

- hosts: web
  tasks:
  - name: create file on web file on web machine
    file:
      dest: ./web-file
      state: '{{file_state}}'

- hosts: all:!db
  tasks:
  - name: create file on all web machines
    file:
      dest: ./web-not-db-file
      state: '{{file_state}}'

- hosts: all:&backup:!web
  tasks:
  - name: create file on all web machines
    file:
      dest: ./backup-file
      state: '{{file_state}}'
